### ISSUE TITLE
Read data from open exoplanet catalogue

### ISSUE THREAD

**Issue by migueldvb** [COINtoolbox/Exoplanets#1]
I think that the python script read_data_Python.py creates a text file that is used for the Poisson analysis. Because the catalogue repository is updated frequently it could be better to read these data directly from a local copy of the catalogue that can be included in the Exoplanets repository using `git submodule`.

**Comment by emilleishida** [comment]
I agree. 

However, this was done in this way because part of the code is done in Python and part is done in R (because we have people with different background). 
So a static data file is easier be read by different users and languages. 
Once we have the analysis up and running we can choose the most recent version of the catalog to construct the final result. 
However, your comment made me realize that we were indeed using a local static version of the table of habitable planets. 
This was changed and the current version of the script reads the online table on the fly. 

It is important to remember anyone doing this analysis to run the python script once in a while before interpreting results.

**Comment by migueldvb** [comment]
OK, that makes sense.
